Stupns Homework
aodarc/LITS009 pull request #3
Opened 2018-08-12 14:43 UTC by stupns

2018-08-13 13:38 UTC, stupns commented
Rewrite

2018-08-13 13:55 UTC, stupns commented
end

2018-08-25 18:33 UTC, aodarc requested changes

2018-08-25 18:33 UTC, aodarc commented on homework/Stupns/homework6.py
> +        a = print('File extension with .py not found')
in this case if you want return None, you should skip `a` variable and use just `return`

2018-08-25 18:33 UTC, aodarc commented on homework/Stupns/homework9.py
> +def numberGenerator(n):
It should generate `simple numbers` !!!

2018-08-25 18:33 UTC, aodarc commented on homework/Stupns/homework9.py
> +    b = a.append(0)
Do you like this code? Two mistakes:
1) You do not need create new variable to append something into list. `.append()` method always returns None
2) Why you didn't use cycle?

2018-08-25 18:33 UTC, aodarc commented on homework/Stupns/homework9.py
> +    print('Work Number generator func ~ms :')
In this homework you should compare two ways to create lists of simple numbers by time. But you didn't .

2018-08-30 17:53 UTC, aodarc requested changes

2018-08-30 17:53 UTC, aodarc commented on homework/Stupns/homework10.py
> +                err += tag.__name__
use string formatting

2018-08-30 17:53 UTC, aodarc commented on homework/Stupns/homework10.py
> +                if name2 == '':
skip second argument

2018-08-30 17:53 UTC, aodarc commented on homework/Stupns/homework10.py
> +                    return name + func(*args2) + new_name
do not concatenate string using plus (+)

2018-09-04 19:33 UTC, closed without merging